server:
  port: 9527
  tomcat:
    accept-count: 1000
    max-connections: 10000

spring:
  application:
    name: seatunnel-web
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8

  ai:
    deepseek:
      api-key: sk-d615692a05d44e8997e993ad4f290a48
      base-url: "https://api.deepseek.com"
      chat:
        options:
          model: deepseek-chat
      embedding:
        enabled: false


  datasource:
    cockpit:
      jdbc-url: jdbc:mariadb://192.168.1.113:3306/seatunnel_web?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: org.mariadb.jdbc.Driver
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-test-query: SELECT 1

  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: seatunnel-web
            instanceId: AUTO
          threadPool:
            threadCount: 40


logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    enabled-by-default: false

monitoring:
  collection:
    enabled: true
    interval: 60000
  jvm:
    interval: 60000
  clean:
    cron: "0 0 2 * * ?"
  application:
    name: "seatunel-web"
  instance:
    id: "seatunel-web-instance"
  thread:
    pool:
      size: 5
      max-size: 10
      queue-capacity: 100


