version: '3.8'

services:
  seatunnel-web:
    image: seatunnel-web:1.0.0
    container_name: seatunnel-web
    ports:
      - "9527:8080"
    environment:
      DB_URL: jdbc:mariadb://192.168.1.113:3306/link_up?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      DB_USERNAME: root
      DB_PASSWORD: 123456

  seatunnel-web-ui:
    image: seatunnel-web-ui:1.0.0
    container_name: seatunnel-web-ui
    restart: always
    ports:
      - "9001:80"
    depends_on:
      - seatunnel-web
    networks:
      - seatunnel-net

networks:
  seatunnel-net:
    driver: bridge